[[ittapi]]
arch = "i686"
git-tree-sha1 = "e597d8730ad63e48c4c8b7aabf271135dca18fdd"
libc = "glibc"
os = "linux"

    [[ittapi.download]]
    sha256 = "358ea573576d503d64121e8e8bc5e1b9c6a64c8f29f06898bd2c8b839470068b"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.25.5+0/ittapi.v3.25.5.i686-linux-gnu.tar.gz"
[[ittapi]]
arch = "i686"
git-tree-sha1 = "c0afcb7bb3c0e19f4ab83ad41be944e9894e7ac2"
libc = "musl"
os = "linux"

    [[ittapi.download]]
    sha256 = "2b9fb01a4f214d7e057d4bb71e91d710004fa09ae363f1f5ef5cafa3d47f8732"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.25.5+0/ittapi.v3.25.5.i686-linux-musl.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "f797fd3c8a84298c5db22b02e8053eacefb3cdae"
os = "macos"

    [[ittapi.download]]
    sha256 = "a37a4c1479ab2be9ba2e9cb76972342b6c7d8c84746570c64cbc4be4d66ee37a"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.25.5+0/ittapi.v3.25.5.x86_64-apple-darwin.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "9c595fc9f26498a6c07134c36a6c3028405ee199"
libc = "glibc"
os = "linux"

    [[ittapi.download]]
    sha256 = "ccbc41ca083a066744df924e2f0eddedf6f128fa7bf8de4e38ec8229d02508b6"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.25.5+0/ittapi.v3.25.5.x86_64-linux-gnu.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "3fa5a5c1a61313ce269b55a2583efe5cdd128d80"
libc = "musl"
os = "linux"

    [[ittapi.download]]
    sha256 = "0f5d3b0844bf7089fc0418a34a5617cd7f3a3004e19a227734b99e29b0c33c8c"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.25.5+0/ittapi.v3.25.5.x86_64-linux-musl.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "2b3fcce71d97b711c490d78cf8e56c4f0d2dc02c"
os = "freebsd"

    [[ittapi.download]]
    sha256 = "fc4fd76d7af574093daa52ef254c57db25e661921af67513933f1cbf910e00dd"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.25.5+0/ittapi.v3.25.5.x86_64-unknown-freebsd.tar.gz"
