[[ittapi]]
arch = "i686"
git-tree-sha1 = "df37525b7d11c326447703c41d91d2a8d1f94add"
libc = "glibc"
os = "linux"

    [[ittapi.download]]
    sha256 = "4f785c0db035a4b90f1c85fcd042dae51eb0d3733d940349f4a94cdf27540c27"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.4+0/ittapi.v3.24.4.i686-linux-gnu.tar.gz"
[[ittapi]]
arch = "i686"
git-tree-sha1 = "22f7826c1c8e44f8583c8b20d2f64379c7574efd"
libc = "musl"
os = "linux"

    [[ittapi.download]]
    sha256 = "ae694b452cc505c72e000f1c285f31511b5e1d925ca7a47c1177c87ca88fe7d7"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.4+0/ittapi.v3.24.4.i686-linux-musl.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "cf19c0bc244ff491048ee4503e649609fad7ee9a"
os = "macos"

    [[ittapi.download]]
    sha256 = "0747eacb9ded1adff2927a07cb60b20fb109acba10e1b9201e2f4ed0d243c912"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.4+0/ittapi.v3.24.4.x86_64-apple-darwin.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "b16fca1cfafcf2e41681d8f75ff141c8dfdcb0d0"
libc = "glibc"
os = "linux"

    [[ittapi.download]]
    sha256 = "08d3b10cfae3eed211300003bf40072cdfd460784abaca1c269197bd8612117c"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.4+0/ittapi.v3.24.4.x86_64-linux-gnu.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "51ee181b73a3dbbf8e6020a31bca696c2a32c348"
libc = "musl"
os = "linux"

    [[ittapi.download]]
    sha256 = "76b455334b192610298fb71bec451d5ae34516ab916d1fe75ae03f9fa2398873"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.4+0/ittapi.v3.24.4.x86_64-linux-musl.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "34ad910e385a1d08bae06675d9b301907401ff2e"
os = "freebsd"

    [[ittapi.download]]
    sha256 = "6da6c2f45fa26bf4616e0a2159c8d29635c9c3351a636f2dfc6ad3c61339b9a6"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.4+0/ittapi.v3.24.4.x86_64-unknown-freebsd.tar.gz"
