[[ittapi]]
arch = "i686"
git-tree-sha1 = "f7190c13d60af5e675c5a303869faf6228b0374b"
libc = "glibc"
os = "linux"

    [[ittapi.download]]
    sha256 = "fcf23ded2956b758334712f078190954c6877389e95266e92fa9251ec5bfbbc4"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.2+0/ittapi.v3.24.2.i686-linux-gnu.tar.gz"
[[ittapi]]
arch = "i686"
git-tree-sha1 = "22f7826c1c8e44f8583c8b20d2f64379c7574efd"
libc = "musl"
os = "linux"

    [[ittapi.download]]
    sha256 = "ae694b452cc505c72e000f1c285f31511b5e1d925ca7a47c1177c87ca88fe7d7"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.2+0/ittapi.v3.24.2.i686-linux-musl.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "f192b09cff5b71fb57adf6b83128d35d0b9556d1"
os = "macos"

    [[ittapi.download]]
    sha256 = "c356f4c46b5b2c8768a02352b7cf37957998ffcb8f489bbe5622a88b73a1b203"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.2+0/ittapi.v3.24.2.x86_64-apple-darwin.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "b16fca1cfafcf2e41681d8f75ff141c8dfdcb0d0"
libc = "glibc"
os = "linux"

    [[ittapi.download]]
    sha256 = "08d3b10cfae3eed211300003bf40072cdfd460784abaca1c269197bd8612117c"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.2+0/ittapi.v3.24.2.x86_64-linux-gnu.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "51ee181b73a3dbbf8e6020a31bca696c2a32c348"
libc = "musl"
os = "linux"

    [[ittapi.download]]
    sha256 = "76b455334b192610298fb71bec451d5ae34516ab916d1fe75ae03f9fa2398873"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.2+0/ittapi.v3.24.2.x86_64-linux-musl.tar.gz"
[[ittapi]]
arch = "x86_64"
git-tree-sha1 = "88a822c04c68d0a9ab22c6ade1c8a68a6b74895d"
os = "freebsd"

    [[ittapi.download]]
    sha256 = "363bb617f79ace43292cbe0a55c124a0302a9a0f1071dedc55100d20bcd8abec"
    url = "https://github.com/JuliaBinaryWrappers/ittapi_jll.jl/releases/download/ittapi-v3.24.2+0/ittapi.v3.24.2.x86_64-unknown-freebsd.tar.gz"
