# Autogenerated wrapper script for ittapi_jll for i686-linux-musl
export libittnotify

JLLWrappers.@generate_wrapper_header("ittapi")
JLLWrappers.@declare_library_product(libittnotify, "libittnotify.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libittnotify,
        "lib/libittnotify.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
